on: 
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        default: V1.0.0
jobs:
  tag_demo:
    runs-on: ubuntu-latest
    steps:
      - name: repo list
        run: |
           curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer  ${{ secrets.demo1 }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Ayyappan-STC/"${{ github.event.repository.name }}"/releases -d '{"tag_name":"${{ github.event.inputs.tag_name }}","target_commitish":"dev","name":"${{ github.event.inputs.tag_name }}","body":"body","draft":false,"prerelease":false,"generate_release_notes":false}'
